### ISSUE TITLE
Interface type error in ipfs name resolve

### ISSUE THREAD

**Issue by cydergoth** [jbenet/go-ipfs#689]
gentoo ~/workspace/bin $ ./ipfs name resolve
panic: interface conversion: interface is string, not util.Key

goroutine 1 [running]:
github.com/jbenet/go-ipfs/core/commands.func·044(0x7f58ffb8e5e0, 0xc208058960, 0x0, 0x0, 0x0, 0x0)
        /home/jcrisp/workspace/src/github.com/jbenet/go-ipfs/core/commands/resolve.go:85 +0x89
github.com/jbenet/go-ipfs/commands.(*response).Marshal(0xc208058960, 0x0, 0x0, 0x0, 0x0)
        /home/jcrisp/workspace/src/github.com/jbenet/go-ipfs/commands/response.go:184 +0x7d5
github.com/jbenet/go-ipfs/commands.(*response).Reader(0xc208058960, 0x0, 0x0, 0x0, 0x0)
        /home/jcrisp/workspace/src/github.com/jbenet/go-ipfs/commands/response.go:204 +0x111
main.(*cmdInvocation).Run(0xc208061180, 0x7f58ffb8cdf8, 0xc208107410, 0x0, 0x0, 0x0, 0x0)
        /home/jcrisp/workspace/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:176 +0x3df
main.main()
        /home/jcrisp/workspace/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:128 +0x52c

goroutine 5 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [runnable]:
net/http.(*persistConn).readLoop(0xc20805c370)
        /usr/lib/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:660 +0xc9f

goroutine 9 [chan receive]:
main.func·012()
        /home/jcrisp/workspace/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:503 +0x63
created by main.(*cmdInvocation).setupInterruptHandler
        /home/jcrisp/workspace/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:525 +0x121

goroutine 18 [select]:
net/http.(*persistConn).writeLoop(0xc20805c370)
        /usr/lib/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:661 +0xcbc
gentoo ~/workspace/bin $ ./ipfs version
ipfs version 0.1.7

**Comment by whyrusleeping** [comment]
Are you running latest master? I remember having this bug mid-PR a while ago, but it was addressed before the merge.

**Comment by cydergoth** [comment]
Pulled it down with 

$ go get -u github.com/jbenet/go-ipfs/cmd/ipfs, so yeah, should be

**Comment by whyrusleeping** [comment]
Any idea how to repro? 
I tried the following:

```
whyrusleeping@alarm ~/g/s/g/j/go-ipfs> git co master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
whyrusleeping@alarm ~/g/s/g/j/go-ipfs> git pull origin master
From github.com:jbenet/go-ipfs
 * branch            master     -> FETCH_HEAD
Already up-to-date.
whyrusleeping@alarm ~/g/s/g/j/go-ipfs> go install ./...
whyrusleeping@alarm ~/g/s/g/j/go-ipfs> ipfs name resolve
QmQ3eMtrRcJKu5YFymDq9QMWgrq4uyaCgm6HGZRuEujKHV
```

**Comment by zignig** [comment]
I'm still getting this on latest master 

75a2975b85908c9decd38c0f1c6fb9e3003e82e6

**Comment by cydergoth** [comment]
I got this from
1) Clone my base gentoo/awesome WM VM
2) emerge go 1.4
3) clone down ipfs and build following the instructions in the wiki page - the single go command line
5) run it from the build dirs

**Comment by cydergoth** [comment]
Is a protocol buffer metadata recompile needed?

**Comment by whyrusleeping** [comment]
no a protobuf problem, i think ive found the issue. It only occurs when a daemon is running, most likely due to the key being converted to a string for JSON transport.

**Comment by whyrusleeping** [comment]
@cydergoth @zignig should be fixed now, could you try it again and let me know?

**Comment by zignig** [comment]
Roger PSSSHT , fix for me.

**Comment by whyrusleeping** [comment]
Cool, closing. Thanks @cydergoth for reporting this!
