### ISSUE TITLE
File Links on WebUI set to localhost, not the actual host

### ISSUE THREAD

**Issue by BrendanBenshoof** [jbenet/go-ipfs#839]
links in the File tab of the Webui point to 127.0.0.1:8080

I run my ipfs node on another ip in my LAN

The webUI can actually parse the config file to provide a correct url for links. (port and IP)

**Comment by BrendanBenshoof** [comment]
I restarted the daemon and links are fixed. I need to find steps to reproduce.

**Comment by travisperson** [comment]
Related to https://github.com/protocol/ipfs-webui/issues/4 and maybe https://github.com/protocol/ipfs-webui/issues/3

**Comment by jbenet** [comment]
I merged https://github.com/protocol/ipfs-webui/pull/13 -- which closed https://github.com/protocol/ipfs-webui/issue/4

**Comment by jbenet** [comment]
I this still a problem? if so pls reopen in https://github.com/protocol/ipfs-webui
